config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :customers,    path: 'cliente',      path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :consultants,  path: 'consultor',    path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :admins,       path: 'admin',        path_names: {sign_in: 'login', sign_out: 'logout'}

  root 'public#index'

  get 'termos' => "public#termos", as: :termos

  get 'quemsomos' => "public#quemsomos", as: :quemsomos

  get 'contato' => "public#contato", as: :contato

  get 'admin', to: 'admin#index', as: 'admin'

  get 'add_item/:item_id', path: 'adicionar', to: 'customer/carts#add_item', as: 'add_item'
  resources :categories, path: 'categoria', only: [:show]
  resources :subcategories, path: 'subcategoria', only: [:show]
  resources :items, path: 'produto', only: [:show]

  namespace :customer , path: 'minha-conta' do

    get 'show', path: 'geral'

    resources :credentials, only: [] do
      put 'update_password', on: :collection
    end
    

    resources :account, path: 'meus-dados', only: ['edit', 'update'], path_names: {update: 'atualizar', edit: 'editar'} do
      get 'edit_address', path: 'editar-enderecos', on: :collection
      put 'update_address', on: :collection
      post 'create_address', on: :collection
      get 'new_address', path: 'novo-endereco', on: :collection
    end

    resources :carts, path: 'carrinho-de-compras' do
      get 'show', path: 'carrinho', on: :member
      post 'shipping', path: 'entrega', on: :member
      post 'freight', path: 'frete', on: :member
      post 'payment', path: 'opcoes-de-pagamento', on: :member
      collection do
        post 'remove_item', path: 'remover'
        post 'update_item', path: 'atualizar-carrinho'
        post 'payment', path: 'pagamento'
      end
    end

    resources :items, path: 'produto', only: [:show]

    resources :orders, path: 'meus-pedidos', only: [:show, :index] do
      get 'search', path: 'buscar', on: :collection
      patch 'order_delivered', on: :member
    end

    resources :orders, path: 'pedidos', only: [:index, :show] do
      post 'credit_card', path: 'carta-de-credito'
      post 'billet', path: 'boleto'
    end

  end

  namespace :admin, path: 'admin' do

    resources :categories, path: 'categorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :subcategories, path: 'subcategorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :items, path: 'produtos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :customers, path: 'clientes', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :consultants, path: 'consultores', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :orders, path: 'pedidos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
    resources :banners, path: 'banners', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :app_info, path: 'app_info', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
  end

end

app/views/admin/index.html.slim
- content_for :head do
  title Forbike - Home

section.title-area.m-b-30
  .container
    h1 Bem vindo, #{current_admin}

section.dashboard.m-b-30
  .container.white-bg.p-40.shadow-box
    .row
      .col-xs-12.col-sm-3.col-md-3
        .card
          .icon
            i.icon.icon-user
          .info-area
            span.text-block= link_to 'Clientes', [:admin, :customers], title: 'Ver todos os clientes'
            h3.blue-text= Customer.count

      .col-xs-12.col-sm-3.col-md-3
        .card
          .icon
            i.icon.icon-user
          .info-area
            span.text-block= link_to 'Consultores', [:admin, :consultants], title: 'Ver todos os consultores'
            h3= Consultant.count

      .col-xs-12.col-sm-3.col-md-3
        .card
          .icon
            i.icon.icon-user
          .info-area
            span.text-block= link_to 'Categorias', [:admin, :categories], title: 'Ver todos os fornecedores'
            h3= Category.count

      .col-xs-12.col-sm-3.col-md-3
        .card
          .icon
            i.icon.icon-user
          .info-area
            span.text-block= link_to 'Sub-categorias', [:admin, :subcategories], title: 'Ver todos os fornecedores'
            h3= Subcategory.count



      .col-xs-12.col-sm-3.col-md-3
        .card
          .icon
            i.icon.icon-list
          .info-area
            span.text-block= link_to 'Pedidos', [:admin, :orders], title: 'Ver todos os pedidos'
            h3 0
    .panel.panel-default.panel-chart
      .panel-heading
        h3.panel-title Vendas / Mês
      .panel-body
        div(width="75%")
          canvas#sales-chart

    hr.gap

- content_for :script do
  javascript:

    $.ajax({
    url: '/admin/get_order_by_month_report', dataType: 'json', cache: true,
    beforeSend: function() {
    },
    success: function(data) {
      var report = data;

          var sales = document.getElementById("sales-chart").getContext("2d");
          var salesData  = {
            labels: [report[0]["month"], report[1]["month"], report[2]["month"], report[3]["month"], report[4]["month"], report[5]["month"]],
            datasets: [
              {
                label: "My First dataset",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: [30, 50, 43, 45, 30, 60, 62]
              },
              {
                label: "My Second dataset",
                fillColor: "rgba(151,187,205,0.2)",
                strokeColor: "rgba(151,187,205,1)",
                pointColor: "rgba(151,187,205,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(151,187,205,1)",
                data: [report[0]["total"], report[1]["total"], report[2]["total"], report[3]["total"], report[4]["total"], report[5]["total"]]
              }
            ]
          };
          var salesChart = new Chart(sales).Line(salesData, {responsive: true});
      },
      error: function(data) {
      }
    });