config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :customers,    path: 'cliente',      path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :consultants,  path: 'consultor',    path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :admins,       path: 'admin',        path_names: {sign_in: 'login', sign_out: 'logout'}

  root 'public#index'

  get 'termos' => "public#termos", as: :termos

  get 'quemsomos' => "public#quemsomos", as: :quemsomos

  get 'contato' => "public#contato", as: :contato

  get 'admin', to: 'admin#index', as: 'admin'

  get 'add_item/:item_id', path: 'adicionar', to: 'customer/carts#add_item', as: 'add_item'
  resources :categories, path: 'categoria', only: [:show]
  resources :subcategories, path: 'subcategoria', only: [:show]
  resources :items, path: 'produto', only: [:show]

  namespace :customer , path: 'minha-conta' do

    get 'show', path: 'geral'

    resources :credentials, only: [] do
      put 'update_password', on: :collection
    end
    

    resources :account, path: 'meus-dados', only: ['edit', 'update'], path_names: {update: 'atualizar', edit: 'editar'} do
      get 'edit_address', path: 'editar-enderecos', on: :collection
      put 'update_address', on: :collection
      post 'create_address', on: :collection
      get 'new_address', path: 'novo-endereco', on: :collection
    end

    resources :carts, path: 'carrinho-de-compras' do
      get 'show', path: 'carrinho', on: :member
      post 'shipping', path: 'entrega', on: :member
      post 'freight', path: 'frete', on: :member
      post 'payment', path: 'opcoes-de-pagamento', on: :member
      collection do
        post 'remove_item', path: 'remover'
        post 'update_item', path: 'atualizar-carrinho'
        post 'payment', path: 'pagamento'
      end
    end

    resources :items, path: 'produto', only: [:show]

    resources :orders, path: 'meus-pedidos', only: [:show, :index] do
      get 'search', path: 'buscar', on: :collection
      patch 'order_delivered', on: :member
    end

    resources :orders, path: 'pedidos', only: [:index, :show] do
      post 'credit_card', path: 'carta-de-credito'
      post 'billet', path: 'boleto'
    end

  end

  namespace :admin, path: 'admin' do

    resources :categories, path: 'categorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :subcategories, path: 'subcategorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :items, path: 'produtos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :customers, path: 'clientes', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :consultants, path: 'consultores', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :orders, path: 'pedidos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
    resources :banners, path: 'banners', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :app_info, path: 'app_info', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
  end

end

app/models/order.rb
# encoding: utf-8
class Order < ActiveRecord::Base
  extend FriendlyId
  friendly_id :number, use: [:slugged, :finders]

  belongs_to :user

  has_many   :items,    class_name: 'OrderItem'
  has_one    :shipping, class_name: 'OrderShipping'

  scope :has_billet, -> { where.not(gateway_url: "") }

  validates :user, presence: true

  accepts_nested_attributes_for :shipping, allow_destroy: true
  accepts_nested_attributes_for :items,    allow_destroy: true

  def self.create_from_cart(cart)
    user = cart.user
    if cart.items.any?
      order = user.orders.build
      # BUILD ORDER ITEMS
      cart.items.each do |product|
        order.items.build(item_id: product.item_id, quantity: product.quantity, price: product.price, total: product.total)
      end
      # BUILD SHIPPING ADDRESS
      address = (user.addresses.shipping[0] or user.addresses[0])
      order.build_shipping(address.attributes.except('id', 'user_id', 'active', 'created_at', 'updated_at')) if(address.present?)
      order.save ? (cart.destroy; order) : false
    else
      false
    end
  end

  def generate_billet(url, id)
    self.billet_url = url
    self.payment_invoice_id = id
    self.save
    self
  end

  def pay_with_credit_card(cc)
    response = MundiPagg.charge_credit_card( (total_with_shipping * 100).to_i, cc)
    raise response.inspect
    raise response.inspect
    if !response["ErrorReport"].present? && response["CreditCardTransactionResultCollection"][0]["Success"]
      self.status = "paid"
      self.save
      raise cc.inspect
    else
      raise response.inspect
    end
  end

  def total_with_shipping
    return self.shipping.present? ? (self.total.to_f + self.shipping.value.to_f) : self.total.to_f
  end

  def freight_dimensions
    dimensions = {length: 0, width: 0, weight: 0, height: 0}
    self.items.each do |item|
      dimensions[:length] += item.item.length
      dimensions[:width] += item.item.width
      dimensions[:weight] += item.item.weight
      dimensions[:height] += item.item.height
    end
    return dimensions
  end

  def generate_freight
    dimensions = freight_dimensions
    return Freight.calculate(self.shipping.zipcode, "83323-090", dimensions[:weight], dimensions[:width], dimensions[:height], dimensions[:length])
  end

  def generate_sedex
    options = generate_freight
    self.shipping.value = options[:sedex].valor
    self.shipping.kind = "SEDEX"
    self.total += self.shipping.value
    self.save
  end

  def generate_pac
    options = generate_freight
    self.shipping.value = options[:pac].valor
    self.shipping.kind = "PAC"
    self.total += self.shipping.value
    self.save
  end


  def self.create_from_cart_no_destroy(cart)
    user = cart.user
    if cart.items.any?
      order = user.orders.build

      # BUILD ORDER ITEMS
      cart.items.each do |product|
        order.items.build(product_id: product.id, quantity: product.quantity, price: product.price, total: product.total)
      end

      # BUILD SHIPPING ADDRESS
      address = (user.addresses.shipping[0] or user.addresses[0])

      order.build_shipping(address.attributes.except('id', 'user_id', 'active', 'created_at', 'updated_at')) if(address.present?)
      order.save ? order : false
    else
      false
    end
  end

  def waiting?
    payment_status && payment_status.eql?('waiting')
  end

  def update_shipping(params)
    return false unless(waiting? or params[:shipping].present?)
    params   = params[:shipping].merge!({kind: 'shipping'})
    shipping = build_shipping(params)
    if shipping.valid?
      customer.addresses.create(params) if customer.addresses.shipping.empty?
      (save; self)
    else
      false
    end
  end

  def update_consultant(id)
    consultant = Consultant.find_by_id(id)
    consultant ? update_attributes(consultant: consultant) : false
  end

  def ready_to_checkout?
    (customer.present? && shipping.present? && consultant.present?)
  end

  def checkout(params)
    return false unless ready_to_checkout?
    update_attributes(params)
  end

  def status_br
    STATUS[payment_status].present? ? STATUS[payment_status] : STATUS["waiting"]
  end

  def gateway_payment_status
    status = Gateway.payment_status(self.payment_invoice_id)
    return false unless status.present?
    self.payment_status = status
    self.save
  end

  def invoice_api
    {id: payment_invoice_id, url: gateway_url}
  end

  def invalid_status?
    return ready_to_checkout? ? Order::STATUS[payment_status] : "Cancelado"
  end

  STATUS = {
    "waiting"   => "Aguardando",
    "pending"   => "Aguardando",
    "confirmed" => "Confirmado",
    "paid"      => "Pago",
    "approved"  => "Aprovado",
    "expired"   => "Expirado",
    "cart"      => "Cart",
    ""          => "Incompleto",
    nil         => "Incompleto"
  }

  PAYMENT_METHODS = { "Boleto" => "bank_slip", "Cartão de crédito" => "credit_card" }

  before_create do |o|
    o.number = CodeGenerator.generate.first(8).upcase
  end

  after_save do |o|
    o.update_columns(slug: o.number.parameterize, total: o.items.collect(&:total).sum)
  end

end

app/controllers/admin/orders_controller.rb
# encoding: utf-8
class Admin::OrdersController < AdminController

  def index
    @orders = Order.all.order(created_at: :desc).page(params[:page]).per(14)
  end

  def search
    @init  = params[:search][:init]
    @end  = params[:search][:end]
    @result = Order.where('created_at >= ? AND created_at <= ?', Date.parse(@init), Date.parse(@end) ).order(created_at: :asc)
    @count = @result.count
    @orders   = Kaminari.paginate_array(@result).page(params[:page])
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.friendly.find(params[:id])
    if @order.update_attributes(order_params)
      flash[:notice] = "Dados do pedido alterado com sucesso!"
      redirect_to [:admin, :orders]
    else
      flash[:danger] = "Não foi possível atualizar o pedido, tente novamente"
      render 'edit'
    end
  end

  def show
    @order = Order.friendly.find(params[:id])
  end


  private

  def order_params
    params.require(:order).permit!
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < CustomerController

  def credit_card
    @order = current_customer.orders.find(params[:order][:id])
    @order.pay_with_credit_card(params[:cc])
    partial = params[:order][:partial]
    return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"} if @order.payment_invoice_id
    response = Gateway.checkout_credit_card(current_customer, token, @order, @order.shipping)
    if response.errors.present?
      redirect_to :back, flash: {notice: response.errors}
    else
      session.delete(:order)
      render 'customer/orders/credit_card'
    end
  end

  def billet
    response = Checkout.create(params[:order][:id])
    #@order = current_customer.orders.find(params[:order][:id])
   # return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"} if @order.payment_invoice_id
    #if @order.save
      #response = MundiPagg.charge_billet(current_customer, @order, @order.shipping)
      #unless response[:status] == true
        #return  redirect_to [:back], notice: "Houve um problema ao salvar o seu pedido. Antes de continuar verifique seu telefone e endereço..."
      #end
      session.delete(:order)
      @url = response.url
      redirect_to @url
  end

  def show
    @order = current_customer.orders.find(params[:id])
  end

  def index
    @orders = current_customer.orders.order(created_at: 'desc').page(params[:page]).per(8)
  end

  def search
    if search_params[:init].present? && search_params[:end].present? && (search_params[:init].to_date < search_params[:end].to_date)
      @orders = current_customer.orders.where('created_at > ? AND created_at < ?', search_params[:init].to_date, search_params[:end].to_date).page(params[:page]).per(8)
      session[:search_init] = search_params[:init]
      session[:search_end] = search_params[:end]
    else
      @orders = current_customer.orders.where('created_at > ? AND created_at < ?', Date.today,  Date.today.end_of_month).page(params[:page]).per(8)
      session[:search_init] = Date.today.to_s_br
      session[:search_end] = Date.today.end_of_month.to_s_br
    end
  end

  def order_delivered
    @order = current_customer.orders.friendly.find(params[:id])
    return redirect_to [:customer_show] unless @order
    response = current_customer.order_delivered(@order.number)
    if response
      flash[:notice] = "O pedido #{@order.number} foi salvo como entregue!"
      redirect_to [:customer_show]
    else
      flash[:notice] = "Não foi possível atualizar o pedido #{@order.number}"
      redirect_to [:customer_show]
    end
  end

  private

  def search_params
    params.require(:search).permit(:init, :end)
  end

  def finish_order_params
    params.require(:order).permit(:delivered_in)
  end

end

app/views/admin/orders/_orders.html.slim
- if params[:action] == "search"
  .section.not-found style="margin-bottom: 20px"
    h3 Sua busca retornou #{pluralize(@orders.count, 'Pedido', 'Pedidos')}.
    = link_to 'Limpar busca'.html_safe, [:admin, :orders], title: "Limpar busca"

- if @orders.any?
  .data-accordion#accordion role="tablist"

    - @orders.each do |order|
      .card
        .card-header id="header-#{order.id}" role="tab"
          .row
            .col-9
              = link_to "#{order.created_at.to_s_br}", "#collapse-#{order.id}", role: 'button', data: { toggle: 'collapse'}, aria: { expanded: 'true', controls: "collapse-#{order.id}"}
            .col-3
              = link_to 'Visualizar', admin_order_path(order), class: "btn btn-success btn-block"

        .collapse id="collapse-#{order.user.id}" role="tabpanel" aria-labelledby="heading-#{order.user.id}" data-parent="#accordion"
          .card-body
            p: strong Dados do cliente
            .row
              .col-6
                p <strong>Nome</strong><br>#{order.user.name}
              .col-3
                p <strong>Telefone</strong><br>#{order.user.phone}
              .col-3
                p <strong>E-mail</strong><br>#{order.user.email}
            p <strong>Endereço</strong><br>#{order.user.addresses.first}

            p: strong Dados do pedido
            .row
              .col
                p <strong>Subtotal</strong><br>#{number_to_currency(order.total)}
              .col
                p <strong>Forma de pagemanto</strong><br>#{order.payment_method}
              .col
                p <strong>Situação do pagemanto</strong><br><span class="text-capitalize">#{order.status_br}</span>
            .row
              .col
                p <strong>Código de Rastreio</strong><br><span class="text-capitalize">#{order.delivery_code}</span>
              .col
                p <strong>Tipo de entrega</strong><br><span class="text-capitalize">#{order.shipping.kind}</span>

            table.table
              thead.thead-light
                tr
                  th width="100"
                  th Item
                  th Valor
                  th.text-center width="60" Qnt.
              tbody
                - order.items.each do |item|
                  - item_price = (item.price.to_f * item.quantity)
                  tr
                    td= image_tag(item.item.s3_image.present? ? item.item.s3_image : "http://placehold.it/185x185", alt: item.to_s, class: "img-thumbnail img-fluid")
                    td
                      strong #{item.item.name}
                      br
                      small= item.item.description
                      - if @target.present? && @target["id"].to_i == item.item["id"]
                        badge.badge-info= @target["info"]
                    td
                      strong= number_to_currency(item.total)
                      br
                      small #{number_to_currency(item.price)} un.
                    td.text-center= item.quantity

- else
  .section.not-found.text-center
    h3 Desculpe, não existem pedidos para exibição.

app/views/admin/orders/billet.html.slim
.container
  .row
   .col-xs-12.col-sm-12.col-md-12
      h2.text-center.payment-success O Boleto para seu pedido foi gerado.
      p.text-center.payment-success Para visualiza-lo clique no botão abaixo!
      .text-center.payment-success= link_to "BOLETO", @pdf, target: "_blank", class: "btn btn-success btn-lg"


- content_for :script do
  javascript:

    $( document ).ready(function() {
      $('.navbar-main').removeClass('navbar-transparent');
      $('#edit-shipping').validate();
    });

app/views/admin/orders/credit_card.html.slim
.container
  .row
   .col-xs-12.col-sm-12.col-md-12
      h2.text-center.payment-success Pagamento concluído
      p.text-center.payment-success Caso queira acompanhar a situação de seu pedido clique no botão abaixo!
      .text-center.payment-success= link_to "Pedidos", [:customer_show], class: "btn btn-success btn-lg"


- content_for :script do
  javascript:

    $( document ).ready(function() {
      $('.navbar-main').removeClass('navbar-transparent');
      $('#edit-shipping').validate();
    });

app/views/admin/orders/index.html.slim
- content_for :head do
  title Forbike - Pedidos

.section.title-area
  .container
    h1 Pedidos
    ol.breadcrumb
      li.breadcrumb-item= link_to 'Dashboard'.html_safe, [:customer_show], title: "Dashboard"
      li.breadcrumb-item.active Pedidos

.section
  .container
    .row
      .col-3
        .section.aside
          = simple_form_for :search, url: [:search, :admin, :orders], html: {class: "form-admin"}, method: :get, remote: true do |f|
            h6 Filtrar Pedidos
            .form-group= f.input :init, as: 'text', input_html: { class: "form-control date", value:"#{session[:search_init].present? ? session[:search_init] : Date.today.to_s_br}"}, label: "Data Inicial:", as: 'search', placeholder: '...'
            .form-group= f.input :end, input_html: { class: "form-control date",value:"#{session[:search_init].present? ? session[:search_end] : (Date.today.end_of_month).to_s_br}" }, label: "Data Final", as: 'search', placeholder: '...'
            = f.submit "Filtrar", class: "btn btn-block"
      .col-xs-12.col-sm-9.col-md-9
        .result-set
          = render 'orders'
        = paginate @orders

    //.row
    //  .col-xs-12.col-sm-3.col-md-3
      //  = simple_form_for :search, url: [:search, :admin, :orders], html: {class: "form-vertical"}, method: :get, remote: true do |f|
        //  .panel.panel-default.squared
          //  .panel-heading.squared: span.panel-title Filtrar Pedidos
          //  .panel-body
          //    .row
          //      .col-xs-12.col-sm-12.col-md-12= f.input :criteria, input_html: { class: "form-control" }, label: "Buscar usuário:", as: 'search', placeholder: '...'
          //  .panel-footer= f.submit "BUSCAR...", class: "btn btn-default btn-block squared"
      //  hr.gap

    //  .col-xs-12.col-sm-9.col-md-9
    //    .result-set= render 'orders'
    //    = paginate @orders

app/views/admin/orders/show.html.slim
.title-area
  .container
    center: h1 Pedidos
    ol.breadcrumb
      li= link_to '<i class="icon icon-home"></i>'.html_safe, [:customer_show], title: "Página inicial"
      li= link_to "Pedidos", [:customer, :orders]
      li.active Pedido: #{@order.number}


.section-half
  .container
    .panel.panel-default
      .panel-heading(role="tab" id="heading#{@order.id}")
        .row
          .col-xs-12.col-sm-6.col-md-6
            = link_to "#{@order.created_at.to_s_br}", "#collapse#{@order.id}", role: "button", class: 'text-left'

      .panel-body
        .row
          .col-xs-12.col-sm-4.col-md-3
            h5 <strong>Forma de pagemanto</strong><br>#{@order.payment_method}
          .col-xs-12.col-sm-4.col-md-3
            h5 <strong>Situação do pagemanto</strong><br><span class="text-capitalize">#{@order.status_br}</span>
          .col-xs-12.col-sm-4.col-md-3
            h5: strong TOTAL<br>#{number_to_currency(@order.total)}
          .col-xs-12.col-sm-4.col-md-3
            h5 <strong>Tipo de entrega</strong><br><span class="text-capitalize">#{@order.shipping.kind}</span>
          .col-xs-12.col-sm-4.col-md-3
            h5 <strong>Código de Rastreio</strong><br><span class="text-capitalize">#{@order.delivery_code}</span>
          - if @order.delivered_in
            .col-xs-12.col-sm-4.col-md-3
              h5: strong Entregue em:<br>#{@order.delivered_in.to_s_br}
          - else
            .col-xs-12.col-sm-4.col-md-3
              h5: strong Aguardando Entrega

        hr
        h4: strong Meus Dados
        .row
          .col-xs-12.col-sm-4.col-md-4
            h5 <strong>Nome</strong><br>#{@order.user.name}
          .col-xs-12.col-sm-4.col-md-4
            h5 <strong>Telefone</strong><br>#{@order.user.phone}
          .col-xs-12.col-sm-4.col-md-4
            h5 <strong>E-mail</strong><br>#{@order.user.email}
        h5 <strong>Endereço</strong><br>#{@order.shipping}
        .table-responsive
          table.table.table-bordered
            thead
              tr
                th
                th Item
                th.text-center Qnt.
                th.text-cent Valor un.
                th Valor

            tbody
              - @order.items.each do |item|
                - item_price = (item.price.to_f * item.quantity)
                tr
                  td.text-center= image_tag(item.item.s3_image.present? ? item.item.s3_image : "http://placehold.it/185x185", alt: item.to_s, class: "img-thumbnail", style: 'max-height: 90px;')
                  td
                    strong #{item.item.name}
                    br
                    small= item.item.description
                    - if @target.present? && @target["id"].to_i == item.item["id"]
                      alert.alert-info= @target["info"]
                  td.text-center
                    strong= item.quantity
                  td
                    strong #{number_to_currency(item.price)} un.
                  td
                    strong= number_to_currency(item.total)


    hr.gap
    .row
      .col-xs-12.col-sm-6-col-md-6
        = link_to "Voltar", [:admin, :orders], class: "btn btn-success"
      - unless @order.delivered_in.present? || @order.payment_status.eql?("waiting")
        .col-xs-12.col-sm-6-col-md-6
          .text-right= link_to "Pedido Entregue!", order_delivered_customer_order_path(@order), method: 'patch', class: "btn btn-danger", data: {confirm: "Tem certeza que o pedido foi entregue? Não é possível desfazer essa operação!!"}
      - if !@order.billet_url.eql?("")
        .col-xs-12.col-sm-6-col-md-6
          .text-right= link_to "Boleto", @order.billet_url, class: "btn btn-success btn-lg", target: :_blank