config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :customers,    path: 'cliente',      path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :consultants,  path: 'consultor',    path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :admins,       path: 'admin',        path_names: {sign_in: 'login', sign_out: 'logout'}

  root 'public#index'

  get 'termos' => "public#termos", as: :termos

  get 'quemsomos' => "public#quemsomos", as: :quemsomos

  get 'contato' => "public#contato", as: :contato

  get 'admin', to: 'admin#index', as: 'admin'

  get 'add_item/:item_id', path: 'adicionar', to: 'customer/carts#add_item', as: 'add_item'
  resources :categories, path: 'categoria', only: [:show]
  resources :subcategories, path: 'subcategoria', only: [:show]
  resources :items, path: 'produto', only: [:show]

  namespace :customer , path: 'minha-conta' do

    get 'show', path: 'geral'

    resources :credentials, only: [] do
      put 'update_password', on: :collection
    end
    

    resources :account, path: 'meus-dados', only: ['edit', 'update'], path_names: {update: 'atualizar', edit: 'editar'} do
      get 'edit_address', path: 'editar-enderecos', on: :collection
      put 'update_address', on: :collection
      post 'create_address', on: :collection
      get 'new_address', path: 'novo-endereco', on: :collection
    end

    resources :carts, path: 'carrinho-de-compras' do
      get 'show', path: 'carrinho', on: :member
      post 'shipping', path: 'entrega', on: :member
      post 'freight', path: 'frete', on: :member
      post 'payment', path: 'opcoes-de-pagamento', on: :member
      collection do
        post 'remove_item', path: 'remover'
        post 'update_item', path: 'atualizar-carrinho'
        post 'payment', path: 'pagamento'
      end
    end

    resources :items, path: 'produto', only: [:show]

    resources :orders, path: 'meus-pedidos', only: [:show, :index] do
      get 'search', path: 'buscar', on: :collection
      patch 'order_delivered', on: :member
    end

    resources :orders, path: 'pedidos', only: [:index, :show] do
      post 'credit_card', path: 'carta-de-credito'
      post 'billet', path: 'boleto'
    end

  end

  namespace :admin, path: 'admin' do

    resources :categories, path: 'categorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :subcategories, path: 'subcategorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :items, path: 'produtos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :customers, path: 'clientes', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :consultants, path: 'consultores', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :orders, path: 'pedidos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
    resources :banners, path: 'banners', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :app_info, path: 'app_info', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  has_many :subcategories
  scope :active, -> { where(active: true)}

  before_save :update_slug


  def to_s
    name
  end

  def items
    _items = Array.new
    _highlights = Array.new
    subcategories.each do |subcategory|
      subcategory.items.active.each do |item|
        if item.highlight
          _highlights.push(item)
        else
          _items.push(item)
        end
      end
    end
    return _highlights + _items
  end


  private


  def update_slug
    self.slug = self.name.parameterize
  end

end

app/controllers/admin/categories_controller.rb
# encoding: utf-8
class Admin::CategoriesController<AdminController

  def index
    @categories =Category.all.page(params[:page]).per(8)
  end

  def new
    @category = Category.new
  end

  def search
    @criteria = params[:search][:criteria]
    criteria = "%#{@criteria}%"
    @result = Category.where('name LIKE ?', criteria).order('name ASC')
    @count = @result.count
    @categories = Kaminari.paginate_array(@result).page(params[:p])
  end

  def show
    @category = Category.friendly.find(params[:id])
    @suppliers = @category.items.collect(&:supplier).uniq
    @suppliers_hash = @suppliers.collect{|s| {"id" => s.id, "name" => s.name, "image" => s.image}}
    @suppliers_hash.each do |h|
      h[:items] = Item.where(category: @category, supplier: h['id']).order(created_at: :desc).map(&:to_api)
      h[:items_count] = h[:items].count
    end
  end


  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Cadastro da categoria #{@category.name} criado com sucesso!"
      redirect_to [:admin, :categories]
    else
      flash[:danger] = "Não foi possível criar o cadastro do categoria #{@category.name}, verifique os campos e tente novamente"
      render 'new'
    end
  end

  def edit
    @category = Category.friendly.find(params[:id])
  end

  def update
    @category = Category.friendly.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:notice] = "Cadastro da categoria #{@category.name} alterado com sucesso!"
      redirect_to [:admin, :categories]
    else
      flash[:danger] = "Não foi possível atualizar o cadastro do categoria #{@category.name}, tente novamente"
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:id, :name, :active)
  end

end

app/controllers/categories_controller.rb
#encoding: utf-8
class CategoriesController < ApplicationController

  skip_before_filter :authenticate_customer!

  def show
    @categories = Category.active
    @category = Category.find(params[:id])
    @subcategories = @category.subcategories.active
    @items = Kaminari.paginate_array(@category.items).page(params[:page]).per(12)
    
    @promos = @items
  end

end

app/views/categories/show.html.slim
- content_for :head do
  title Produtos #{@category.name} | Forbike
  meta name="description" content=""

.section.slider-page
  .container
    h1 #{@category.name}
    ol.breadcrumb
      li.breadcrumb-item= link_to "Home", [:root], title: 'Home'
      li.breadcrumb-item.active #{@category.name}

.section.mb-90
  .container
    .row
      .col-12.col-sm-3.col-md-3.sidebar
        h2 Subcategorias
        ul.nav.flex-column
          - @category.subcategories.active.each do |s|
            li.nav-item
              = link_to "#{s.name}", [s], title: s.name, role: 'button', class: 'nav-link'

      .col-12.col-sm-9.col-md-9
        .products-wrap.section
          .row
            - @items.each do |item|
              .col-12.col-sm-4.col-md-3
                .product-item.section
                  = link_to(image_tag(item.s3_image, alt: item.name, class: 'img-fluid category_img'), [item], title: item.name)
                  h3= link_to "#{item.name}", [item], title: item.name
                  h4= number_to_currency(item.price)

                  - if current_customer
                    = link_to "Adicionar", [:add_item, item_id: item.id], class: "btn btn-block", title: item.name, remote: true, data: {toggle: 'modal', target: '#modalWindow'}
                  - else
                    = link_to "Adicionar", [:new, :user, :session], class: "btn btn-block", title: item.name

        .section
          = paginate @items

        - unless @items.present?
          .text-center
            h3 Nenhum item cadastrado para #{@category}

- content_for :script do
  javascript:
    $(document).on('ready', function(){
      $('.navbar-main').removeClass('navbar-transparent');
    });