config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :customers,    path: 'cliente',      path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :consultants,  path: 'consultor',    path_names: {sign_in: 'login', sign_up: 'cadastre-se', sign_out: 'logout'}
  devise_for :admins,       path: 'admin',        path_names: {sign_in: 'login', sign_out: 'logout'}

  root 'public#index'

  get 'termos' => "public#termos", as: :termos

  get 'quemsomos' => "public#quemsomos", as: :quemsomos

  get 'contato' => "public#contato", as: :contato

  get 'admin', to: 'admin#index', as: 'admin'

  get 'add_item/:item_id', path: 'adicionar', to: 'customer/carts#add_item', as: 'add_item'
  resources :categories, path: 'categoria', only: [:show]
  resources :subcategories, path: 'subcategoria', only: [:show]
  resources :items, path: 'produto', only: [:show]

  namespace :customer , path: 'minha-conta' do

    get 'show', path: 'geral'

    resources :credentials, only: [] do
      put 'update_password', on: :collection
    end
    

    resources :account, path: 'meus-dados', only: ['edit', 'update'], path_names: {update: 'atualizar', edit: 'editar'} do
      get 'edit_address', path: 'editar-enderecos', on: :collection
      put 'update_address', on: :collection
      post 'create_address', on: :collection
      get 'new_address', path: 'novo-endereco', on: :collection
    end

    resources :carts, path: 'carrinho-de-compras' do
      get 'show', path: 'carrinho', on: :member
      post 'shipping', path: 'entrega', on: :member
      post 'freight', path: 'frete', on: :member
      post 'payment', path: 'opcoes-de-pagamento', on: :member
      collection do
        post 'remove_item', path: 'remover'
        post 'update_item', path: 'atualizar-carrinho'
        post 'payment', path: 'pagamento'
      end
    end

    resources :items, path: 'produto', only: [:show]

    resources :orders, path: 'meus-pedidos', only: [:show, :index] do
      get 'search', path: 'buscar', on: :collection
      patch 'order_delivered', on: :member
    end

    resources :orders, path: 'pedidos', only: [:index, :show] do
      post 'credit_card', path: 'carta-de-credito'
      post 'billet', path: 'boleto'
    end

  end

  namespace :admin, path: 'admin' do

    resources :categories, path: 'categorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :subcategories, path: 'subcategorias', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :items, path: 'produtos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :customers, path: 'clientes', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :consultants, path: 'consultores', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :orders, path: 'pedidos', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
    resources :banners, path: 'banners', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end

    resources :app_info, path: 'app_info', path_names: {edit: 'editar', new: 'novo'} do
      get 'search', on: :collection
    end
    
  end

end

app/models/customer.rb
class Customer < User
  has_many :addresses, foreign_key: 'user_id', dependent: :destroy
  accepts_nested_attributes_for :addresses
end

app/controllers/admin/customers_controller.rb
# encoding: utf-8
class Admin::CustomersController < AdminController

  def index
    @customers = Customer.all.order(created_at: :desc).page(params[:page]).per(8)
  end

  def search
    @criteria  = params[:search][:criteria]
    criteria   = "%#{@criteria}%"
    @result    = Customer.where('name LIKE ? OR email LIKE ?', criteria, criteria).order('name ASC')
    @count = @result.count
    @customers   = Kaminari.paginate_array(@result).page(params[:page])
  end

  def new
    @customer = Customer.new
    @type = @customer.class
    @customer.addresses.build
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      flash[:notice] = "Cadastro do usuário #{@customer.name} criado com sucesso!"
      redirect_to [:admin, :customers]
    else
      flash[:danger] = "Não foi possível criar o cadastro do usuário #{@customer.name}, verifique os campos e tente novamente"
      render 'new'
    end
  end

  def edit
    @customer = Customer.find(params[:id])
    @type = @customer.class
  end

  def update
    @customer = Customer.friendly.find(params[:id])
    if @customer.update_attributes(customer_params)
      flash[:notice] = "Cadastro do usuário #{@customer.name} alterado com sucesso!"
      redirect_to [:admin, :customers]
    else
      flash[:danger] = "Não foi possível atualizar o cadastro do usuário #{@customer.name}, tente novamente"
      render 'edit'
    end
  end

  def show
    @customer = Customer.friendly.find(params[:id])
  end


  private

  def customer_params
    params.require(:customer).permit(:id, :name, :username, :email, :password, :phone, :identifier, :active, addresses_attributes:[:id, :user_id, :zipcode, :street, :district, :number, :kind, :state, :city])
  end

end

app/controllers/customer/account_controller.rb
#encoding: utf-8
class Customer::AccountController < CustomerController

  def edit
    @user = current_customer
  end

  def update
    @user = current_customer
    if @user.update_attributes(customer_params)
      redirect_to [:customer_show], notice: "Dados atualizados com sucesso!"
    else
      render 'edit'
    end
  end

  def edit_address
    @addresses = current_customer.addresses
  end

  def update_address
    if address_params['id'].present?
      @address = Address.find(address_params[:id])
      if @address.update_attributes(address_params)
        flash[:notice] = "Endereço atualizado com sucesso!"
      else
        flash[:notice] = "Ocorreu um problema na atualização do endereço, verifique os dados informados e tente novamente!"
      end
    else
      @address = Address.new(address_params)
      if @address.save
        flash[:notice] = "Endereço criado com sucesso!"
      else
        flash[:notice] = "Ocorreu um problema ao criar o endereço, verifique os dados e tente novamente!"
      end
    end
    redirect_to edit_address_customer_account_index_path()
  end

  def new_address
    current_customer.addresses.build
    @addresses = current_customer.addresses
    render 'edit_address'
  end

  private

  def address_params
    params.require(:address).permit(:id, :district, :user_id, :zipcode, :street, :district, :number, :kind, :state, :city)
  end

  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :username, :mobile, :identifier, :image, addresses_attributes:[:id, :district, :user_id, :zipcode, :street, :district, :number, :kind, :state, :city])
  end

end

app/controllers/customer/carts_controller.rb
class Customer::CartsController < CustomerController
  before_action :cart, only: [:add_item, :remove_item, :update_item, :show]
  skip_before_action :authenticate_customer, only: [:add_item]

  def show

  end

  def add_item
    return redirect_to [:customer_session] unless current_customer
    @item = Item.friendly.find(params[:item_id])
    hash_item = {items: [id: @item.id, quantity: 1]}
    @cart = @cart.push(hash_item)
    @items_count = @cart.items.count
    # render partial: 'add_item'
  end

  def remove_item
    hash_item = {items: [id: params[:id]]}
    @cart = @cart.remove(hash_item)
  end

  def update_item
    quantity =  params[:cart][:cart_item][:quantity]
    item = params[:cart][:cart_item][:id]
    availability_response = @cart.item_available?(item, quantity)
    if availability_response[:available]
      item = {'id' => params[:cart][:cart_item][:id], 'quantity' => params[:cart][:cart_item][:quantity]}
      @target = {"id" => params[:cart][:cart_item][:id], "info" => "Quantidade atualizada!"}
      hash_item = {items: [id: params[:cart][:cart_item][:id], quantity: params[:cart][:cart_item][:quantity]]}
      @cart = @cart.update(hash_item)
    else
      item = {'id' => params[:cart][:cart_item][:id], 'quantity' => availability_response[:max_amount]}
      @target = {"id" => params[:cart][:cart_item][:id], "info" => "A quantidade máx disponível é #{availability_response[:max_amount]}!"}
      hash_item = {items: [id: params[:cart][:cart_item][:id], quantity: availability_response[:max_amount]]}
      @cart = @cart.update(hash_item)
    end
  end

  def shipping
    # @cart = Cart.find(params[:id])
    @order = order
    unless @order
      session.delete(:cart)
      session.delete(:order)
      return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"}
    end
    unless !@order.payment_invoice_id
      session.delete(:cart)
      session.delete(:order)
      return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"}
    end
    @shipping = @order.build_shipping(current_customer.addresses.first.to_hash)
    @order.save
    @freight = @order.generate_freight
  end

  def consultant
    @order = order
    return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"} unless @order.payment_status.eql?("waiting") || @order.payment_status.eql?("cart")
    if @order.update_attributes(order_params)
      @consultants = current_user.consultants_near.uniq
      @favorites = current_customer.favorite_consultants - @consultants
      @order
    else
      flash[:notice] = "Ocorreu um problema ao salvar os dados de entrega, preencha os campos obrigatórios e tente novamente"
      redirect_to [:root]
    end
  end

  def order
    if current_customer && session[:cart].present? && !session[:order].present?
      @order = Order.create_from_cart(cart)
      session[:order] = @order.id
      session.delete(:cart)
      @cart = nil
    elsif session[:order].present?
      @order = current_customer.orders.find(session[:order])
    else
      return false
    end
    @order
  end

  def freight
    @order = order
    if @order.shipping.update_attributes(shipping_attributes[:shipping_attributes])
      @shipping = @order.shipping
      @freight = @order.generate_freight
      render 'shipping'
    else
      # @freight = @order.generate_freight
      flash[:notice] = "Não foi possível calcular o frete, verifique os campos e tente novamente."
    end
  end

  def cart
    if current_customer && session[:cart]
      @cart = current_customer.carts.find(session[:cart])
    else
      @cart = current_customer.carts.build
      @cart.save
      session[:cart] = @cart.id
    end
  end

	def payment
        @order = order
        unless params[:order][:shipping_attributes][:kind].eql?("Retirar")
            if @order.shipping.state.downcase.eql?("pr")
                #raise params[:order].inspect 
                if params[:order][:shipping_attributes][:kind].eql?("SEDEX")
                    @order.generate_sedex
                else
                    @order.generate_pac
                end
            else
                return redirect_to :root, flash: {notice: "Só entregamos no Paraná!"}
            end
        end
  end

  private

  def order_params
    params.require(:order).permit(:id, shipping_attributes: [:id, :order_id, :zipcode, :street, :district, :number, :kind, :state, :city])
  end

  def shipping_attributes
    params.require(:order).permit(shipping_attributes: [:id, :order_id, :zipcode, :street, :district, :number, :kind, :state, :city])
  end

  def cart_params
    params.require(:cart).permit(:id, items_attributes: [:id, :quantity])
  end

end

app/controllers/customer/credentials_controller.rb
#encoding: utf-8
class Customer::CredentialsController < CustomerController
  skip_before_action :authenticate_customer, only: [:update_password]

  def update_password
    user = User.where(reset_password_token: params[:user][:reset_password_token]).first
    response = user.reset_password(params[:user][:password], params[:user][:password_confirmation])
    if response
      flash[:notice] = "Senha alterada com sucesso"
    else
      flash[:notice] = "Não foi possível alterar a senha, verifique se a confirmação de senha e a senha são iguais e se a senha tem mais de 6 caracteres"
    end
    redirect_to [:root]
  end

  
  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :username, :mobile, :identifier, :image, addresses_attributes:[:id, :district, :user_id, :zipcode, :street, :district, :number, :kind, :state, :city])
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < CustomerController

  def credit_card
    @order = current_customer.orders.find(params[:order][:id])
    @order.pay_with_credit_card(params[:cc])
    partial = params[:order][:partial]
    return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"} if @order.payment_invoice_id
    response = Gateway.checkout_credit_card(current_customer, token, @order, @order.shipping)
    if response.errors.present?
      redirect_to :back, flash: {notice: response.errors}
    else
      session.delete(:order)
      render 'customer/orders/credit_card'
    end
  end

  def billet
    response = Checkout.create(params[:order][:id])
    #@order = current_customer.orders.find(params[:order][:id])
   # return redirect_to :root, flash: {notice: "Esse pedido já foi pago ou está aguardando pagamento"} if @order.payment_invoice_id
    #if @order.save
      #response = MundiPagg.charge_billet(current_customer, @order, @order.shipping)
      #unless response[:status] == true
        #return  redirect_to [:back], notice: "Houve um problema ao salvar o seu pedido. Antes de continuar verifique seu telefone e endereço..."
      #end
      session.delete(:order)
      @url = response.url
      redirect_to @url
  end

  def show
    @order = current_customer.orders.find(params[:id])
  end

  def index
    @orders = current_customer.orders.order(created_at: 'desc').page(params[:page]).per(8)
  end

  def search
    if search_params[:init].present? && search_params[:end].present? && (search_params[:init].to_date < search_params[:end].to_date)
      @orders = current_customer.orders.where('created_at > ? AND created_at < ?', search_params[:init].to_date, search_params[:end].to_date).page(params[:page]).per(8)
      session[:search_init] = search_params[:init]
      session[:search_end] = search_params[:end]
    else
      @orders = current_customer.orders.where('created_at > ? AND created_at < ?', Date.today,  Date.today.end_of_month).page(params[:page]).per(8)
      session[:search_init] = Date.today.to_s_br
      session[:search_end] = Date.today.end_of_month.to_s_br
    end
  end

  def order_delivered
    @order = current_customer.orders.friendly.find(params[:id])
    return redirect_to [:customer_show] unless @order
    response = current_customer.order_delivered(@order.number)
    if response
      flash[:notice] = "O pedido #{@order.number} foi salvo como entregue!"
      redirect_to [:customer_show]
    else
      flash[:notice] = "Não foi possível atualizar o pedido #{@order.number}"
      redirect_to [:customer_show]
    end
  end

  private

  def search_params
    params.require(:search).permit(:init, :end)
  end

  def finish_order_params
    params.require(:order).permit(:delivered_in)
  end

end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  before_filter :authenticate_customer!, except: [:update_password]

  def index
    redirect_to [:root]
  end

  def show
    @categories = Category.active
    @user = current_customer
    @orders = current_customer.orders.page(params[:page]).per(5)
    @orders_waiting = current_customer.orders
    @orders_waiting = Kaminari.paginate_array(@orders_waiting).page(params[:page]).per(5)
    @pending_orders = current_customer.orders
    @pending_orders = Kaminari.paginate_array(@pending_orders).page(params[:page]).per(5)
  end

  def edit
    @user = current_customer
    @type = "Customer"
  end

  def update
    @user = current_customer
    if @user.update_attributes(customer_params)
      flash[:notice] = "Cadastro atualizado!"
    else
      flash[:alert] = "Ocorreu um problema ao atualizar o cadastro: #{@user.errors.messages}"
    end
    bypass_sign_in(@user)
    redirect_to [current_customer]
  end

  def consultant
    @consultant = Consultant.friendly.find(params[:consultant_id])
    @favorite = UserFavorite.where(consultant: @consultant, customer: current_customer).first
    @favorite = current_customer.favorites.build unless @favorite
  end

  def order
    @order = current_customer.orders.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :identifier, :phone, :password, :image, suppliers_ids:[], addresses_attributes: [:id, :user_id, :street, :number, :zipcode, :kind, :district, :city_id, :state_id, :latitude, :longitude])
  end

end

app/views/customer/order.html.slim
.container
  table.table.order-table
    tr
      th(width="82px") #
      th Descrição do item
      th(width="150px") Valor R$
      th Quantidade
      th(width="100px")
    - @order.items.each do |item|
      - item_price = (item.price.to_f * item.quantity)
      tr
        td= image_tag(item.item.s3_image.present? ? item.item.s3_image : "http://placehold.it/185x185", alt: item.to_s, class: "img-thumbnail")
        td
          p
            strong.cblue #{item.item.name}
          p
            small.text-block= item.item.description
          - if @target.present? && @target["id"].to_i == item.item["id"]
            p
              alert.alert-info= @target["info"]
        td
          p
            strong.text-block.cgreen= number_to_currency(item.total)
          p
            small #{number_to_currency(item.price)} un.
        td
          = item.quantity

    tr
      td(colspan="5" class="bclean")
        <strong>Subtotal: <span class="cgreen btn-mr">#{number_to_currency(@order.total.to_f)}</span></strong>
  hr.gap
  = link_to "Voltar", [:customer, id: @order.customer.username], class: "btn btn-success"

- content_for :script do
  javascript:
    $(document).on('ready', function(){
      $('.navbar-main').removeClass('navbar-transparent');
    });

app/views/customer/show.html.slim
- content_for :head do
  title Forbike | Minha Conta
  meta name="description" content=""

.section.slider-page
  .container
    h1 Minha Conta
    ol.breadcrumb
      li.breadcrumb-item= link_to "Home", [:root], title: 'Home'
      li.breadcrumb-item.active Minha Conta


.section.mb-90
  .container.item-details
    .row
      .col-12.col-sm-6.col-md-6
        h3 Meus Dados
        p <strong>Nome</strong><br> #{@user.name}
        p <strong>Telefone</strong><br> #{@user.phone}
        p <strong>Data de cadastro</strong><br> #{l(@user.created_at, format: :custom)}
        p <strong>Endereço</strong><br> #{@user.addresses.first}

        = link_to "Editar meus dados", edit_customer_account_path(@user), class: 'btn btn-account'
        = link_to "Editar meus endereços", edit_address_customer_account_index_path(), class: 'btn btn-account'

      .col-12.col-sm-6.col-md-6
        h3 Meus Pedidos
        - if @orders.present?
          #accordion.panel-group aria-multiselectable="true" role="tablist"
            - @orders.each do |o|
              .panel.panel-default
                .panel-heading role="tab" id="heading1#{o.id}"
                  .row
                    .col-xs-12.col-sm-6.col-md-6
                      = link_to "#{l(o.created_at, format: :long)}", "#collapse1#{o.id}", aria: {controls: "collapse1#{o.id}", expanded: 'false'}, data: {parent: '#accordion', toggle: 'collapse'}, role: 'button'
                    .col-xs-12.col-sm-6.col-md-6= link_to "Detalhes", customer_order_path(o), class: 'btn btn-blue pull-right'
                .panel-collapse.collapse(aria-labelledby="heading1#{o.id}" role="tabpanel" id="collapse1#{o.id}")
                  .panel-body
                    .row
                      .col-xs-12.col-sm-6.col-md-6
                        p <strong>Total: </strong>#{number_to_currency(o.total)}
                        p <strong>Modo de Pagamento: </strong><br>#{o.payment_method}
                        p <strong>Status do Pagamento: </strong> #{o.status_br}

        - else
          p Não há pedidos para exibir...

        h3 Boletos pendentes
        - if @orders_waiting.present?
          - @orders_waiting.each do |ow|
            .panel.panel-default
              .panel-heading role="tab" id="heading#{ow.id}"
                .row
                  .col-xs-12.col-sm-6.col-md-6

                    = link_to "#{l(ow.created_at, format: :long)}", "#collapse#{ow.id}", aria: {controls: "collapse#{ow.id}", expanded: 'false'}, data: {parent: '#accordion', toggle: 'collapse'}, role: 'button'
                  .col-xs-12.col-sm-6.col-md-6= link_to "Detalhes", customer_order_path(ow), class: 'btn btn-blue pull-right'
              .panel-collapse.collapse(aria-labelledby="heading#{ow.id}" role="tabpanel" id="collapse#{ow.id}")
                .panel-body
                  .row
                    .col-xs-12.col-sm-6.col-md-6
                      p <strong>Total: </strong>#{number_to_currency(ow.total)}
                      p <strong>Modo de Pagamento: </strong><br>#{ow.payment_method}
                      p <strong>Status do Pagamento: </strong> #{ow.status_br}
                      = link_to "Boleto", ow.billet_url, class: "btn btn-success", target: :_blank


        - else
          p Não há pedidos para exibir...


- content_for :script do
  javascript: